/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl.edu.pw.medcomplexsoft.gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import pl.edu.pw.medcomplexsoft.model.Patient;

/**
 *
 * @author kubix
 */
public class PatientPanel extends javax.swing.JFrame {
    private Patient loggedPatient;

    /**
     * Creates new form PatientPanel
     */
    public PatientPanel(Patient patient) {
        initComponents();
        loggedPatient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        changePasswordItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        prescriptionMenu = new javax.swing.JMenu();
        prescpriptionListMenu = new javax.swing.JMenuItem();
        appointmentMenu = new javax.swing.JMenu();
        appointmentListMenu = new javax.swing.JMenuItem();
        doctorsMenu = new javax.swing.JMenu();
        doctorsItem = new javax.swing.JMenuItem();
        serviceMenu = new javax.swing.JMenu();
        servicesItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel pacjenta");
        setSize(new java.awt.Dimension(1200, 900));

        jMenu1.setText("Plik");

        changePasswordItem.setText("Zmień hasło");
        changePasswordItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordItemActionPerformed(evt);
            }
        });
        jMenu1.add(changePasswordItem);

        logoutMenuItem.setText("Wyloguj");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoutMenuItem);

        exitItem.setText("Wyjście");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitItem);

        jMenuBar1.add(jMenu1);

        prescriptionMenu.setText("Moje Recepty");

        prescpriptionListMenu.setText("Lista recept");
        prescpriptionListMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescpriptionListMenuActionPerformed(evt);
            }
        });
        prescriptionMenu.add(prescpriptionListMenu);

        jMenuBar1.add(prescriptionMenu);

        appointmentMenu.setText("Moje wizyty");

        appointmentListMenu.setText("Lista wizyt");
        appointmentListMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentListMenuActionPerformed(evt);
            }
        });
        appointmentMenu.add(appointmentListMenu);

        jMenuBar1.add(appointmentMenu);

        doctorsMenu.setText("Lekarze");

        doctorsItem.setText("Przeglądaj");
        doctorsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorsItemActionPerformed(evt);
            }
        });
        doctorsMenu.add(doctorsItem);

        jMenuBar1.add(doctorsMenu);

        serviceMenu.setText("Usługi");

        servicesItem.setText("Przeglądaj");
        servicesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesItemActionPerformed(evt);
            }
        });
        serviceMenu.add(servicesItem);

        jMenuBar1.add(serviceMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prescpriptionListMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescpriptionListMenuActionPerformed
        PrescriptionListDialog prescriptionListDialog = new PrescriptionListDialog(null, true, loggedPatient);
        prescriptionListDialog.setLocationRelativeTo(this.rootPane);
        prescriptionListDialog.showDialog();
    }//GEN-LAST:event_prescpriptionListMenuActionPerformed

    private void appointmentListMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentListMenuActionPerformed
        AppointmentsList appointmentList = new AppointmentsList(null, true, loggedPatient);
        appointmentList.setLocationRelativeTo(this.rootPane);
        appointmentList.showDialog();
    }//GEN-LAST:event_appointmentListMenuActionPerformed

    private void doctorsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorsItemActionPerformed
        DoctorListDialog doctorListDialog = new DoctorListDialog(null, true, loggedPatient);
        doctorListDialog.setLocationRelativeTo(this.rootPane);
        doctorListDialog.showDialog();
    }//GEN-LAST:event_doctorsItemActionPerformed

    private void servicesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesItemActionPerformed
        ServiceListDialog serviceListDialog = new ServiceListDialog(null, true, loggedPatient);
        serviceListDialog.setLocationRelativeTo(this.rootPane);
        serviceListDialog.showDialog();
    }//GEN-LAST:event_servicesItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemActionPerformed

    private void changePasswordItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordItemActionPerformed
        ChangePasswordDialog changePasswordDialog = new ChangePasswordDialog(null, true, loggedPatient);
        changePasswordDialog.setLocationRelativeTo(this.rootPane);
        changePasswordDialog.showDialog();
    }//GEN-LAST:event_changePasswordItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        int selection = JOptionPane.showConfirmDialog(this, "Czy na pewno chcesz się wylogować?", "Wylogowywanie",
                                                      JOptionPane.OK_CANCEL_OPTION);
        if(selection == JOptionPane.OK_OPTION) {
            dispose();
            JFrame loginWindow = new LoginWindow();
            loginWindow.setVisible(true);
        }
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientPanel(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem appointmentListMenu;
    private javax.swing.JMenu appointmentMenu;
    private javax.swing.JMenuItem changePasswordItem;
    private javax.swing.JMenuItem doctorsItem;
    private javax.swing.JMenu doctorsMenu;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuItem prescpriptionListMenu;
    private javax.swing.JMenu prescriptionMenu;
    private javax.swing.JMenu serviceMenu;
    private javax.swing.JMenuItem servicesItem;
    // End of variables declaration//GEN-END:variables
}
